name: ${name}
main: jp.azisaba.main.resourceworld.ResourceWorld
version: ${version}
author: siloneco
description: ${description}
softdepend: [Multiverse-Core, WorldEdit, FastAsyncWorldEdit]
api-version: '1.21'
commands:
  resourceworld:
    aliases: ["rw", "resourcew", "rworld"]
    usage: "/{LABEL} [recreate | protect | next]"
    permission: resourceworld.command.resourceworld
    permission-message: You dont have permission to perform this command.
permissions:
  resourceworld.command.resourceworld:
    default: true
  resourceworld.command.resourceworld.admin:
    default: op
  resourceworld.centerprotect.bypass:
    default: op
